#!/usr/bin/env lua
local socket = require "socket"

local server = socket.bind("0.0.0.0", 8081)

while true do
  local client = server:accept()
  if client then
    --"HTTP/1.1 200 OK\nRefresh: 1\n\n$(vcgencmd measure_temp)\n\n$(pinctrl 26,27 | sed -E 's/^.+ \| //m')"
    while true do
      local tp = io.popen("vcgencmd measure_temp", "r")
      local pp = io.popen("pinctrl 26,27 | sed -E 's/^.+ \\| //m'", "r")
      if tp and pp then
        local tr = tp:read "*a"
        local pr = pp:read "*a"
        tp:close()
        pp:close()
        break
      else
        if tp then tp:close() end
        if pp then pp:close() end
	socket.select(nil, nil, 0.01)
      end
    end
    local body = ("%s\n%s"):format(tr, pr)
    client:send(("HTTP/1.1 200 OK\nRefresh: 1\nConnection: close\nContent-Length: %d\n\n%s"):format(#body, body))
  end
end

